# 基本連線設定
listening-port=3478
listening-ip=0.0.0.0      # 監聽所有介面
# 填寫這台伺服器的內網固定 IP
external-ip=192.168.1.100

# 封閉環境必備：允許使用私有 IP 進行中繼
allow-loopback-addresses
cli-password=secretcp
ACL-del-check
no-tls
no-dtls


# 驗證機制 (封閉環境建議先用靜態，穩定後再換 REST API)
lt-cred-mech
user=osce:osce
realm=osce.local

# 關鍵：開放 UDP 埠段（防火牆也必須同步開放）
min-port=49152
max-port=63

# 日誌 (除錯用)
no-stdout-log
verbose