FROM ubuntu:24.04

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl git build-essential wget software-properties-common \
    && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*

COPY ./osce-frontend /app/osce-frontend 
WORKDIR /app/osce-frontend
