server {
    listen 80;
    # 導向 HTTPS
    return 301 https://$host:12000$request_uri;
}

server {
    listen 443 ssl;
    server_name 118.163.52.174;

    ssl_certificate     /etc/ssl/certs/fullchain.pem;
    ssl_certificate_key /etc/ssl/private/privkey.pem;

    # 限制 Nginx 與後端通訊使用 HTTP/1.1，避免 Gunicorn 報錯
    proxy_http_version 1.1;
    proxy_set_header Connection "";

    root /usr/share/nginx/html;
    index index.html;

    location /admin/ {
        alias /usr/share/nginx/html/admin/;
        try_files $uri $uri/ /admin/index.html;
    }

     location /user/ {
        alias /usr/share/nginx/html/user/;
        try_files $uri $uri/ /user/index.html;
    }

    location /api/ {
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme; # 告訴 Django 這是 HTTPS
    }

    location /ai-api/ {
        proxy_pass http://ai-backend:8007/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 根據你的 Django 日誌，修正靜態路徑映射
    location /static/ {
        alias /app/osce-backend/static/; 
    }
}