FROM ubuntu:24.04

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl git build-essential wget software-properties-common \
 && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
 && apt-get install -y nodejs \
 && rm -rf /var/lib/apt/lists/*

ARG GITHUB_TOKEN
RUN git clone  -b enhancement/ocse_backend_api --single-branch https://${GITHUB_TOKEN}@github.com/OSCE-members/osce.git

WORKDIR /app/osce

RUN npm install