version: "3.9"

networks:
  app-network:
    driver: bridge

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - /home/osce/CSMU/CSMU/backend_api/db:/app/CSMU/backend_api/db
      - /home/osce/CSMU/CSMU/backend_api/log:/app/CSMU/backend_api/log
      - /home/osce/CSMU/CSMU/backend_api/images:/app/CSMU/backend_api/images
    working_dir: /app/CSMU/backend_api
    ports:
      - "8001:8000"
    command: >
      bash -c "
      python3.13 manage.py insert_initial_data &&
      python3.13 manage.py makemigrations &&
      python3.13 manage.py migrate &&
      python3.13 manage.py collectstatic --noinput --settings=backend_api.settings &&
      exec gunicorn backend_api.wsgi:application --bind 0.0.0.0:8000 --workers 3
      "
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    command: > 
      bash -c "
        npm run build:admin && 
        npm run build:user
        "
    volumes:
      - ./dist:/app/osce/dist
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "12001:80"
      - "12000:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./dist:/usr/share/nginx/html
      - ./static:/app/CSMU/backend_api/static
      - ./fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - ./privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network