'''
Django settings for backend_api project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
'''
from sre_parse import WHITESPACE
import os
from http.cookiejar import debug
from pathlib import Path
from logging.handlers import SysLogHandler
from dotenv import load_dotenv

load_dotenv()

AUTH_USER_MODEL = 'mgmt.User'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/cRhecklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dwk@c#54tcwepfau*h9ru!7q6!-fat4y7t7cs462#$iti*s2k7'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() in ['true']

# Build paths inside the project like this: BASE_DIR / 'subdir'.
if not DEBUG and os.getenv('BASE_DIR'):
    BASE_DIR = os.getenv('BASE_DIR')
else:
    BASE_DIR = Path(__file__).resolve().parent.parent

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    ## new adds
    'rest_framework',
    'rest_framework.authtoken',
    'mgmt.apps.MgmtConfig',
    'osce.apps.OsceConfig',
    'rules.apps.AutodiscoverRulesConfig',
    'drf_spectacular',
    'corsheaders',
    'channels',
]

ASGI_APPLICATION = 'backend_api.routing.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'exceptions.csmu_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'osce backend API',
    'DESCRIPTION': 'osce backend API',
    'VERSION': '1.0.0',
    'DEFAULT_GENERATOR_CLASS': 'backend_api.spectacular_schema_generators.CSMUSchemaGenerator',
    'COMPONENT_SPLIT_REQUEST': True
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'middleware.logging.ActivityMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'backend_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


db_path = f'{BASE_DIR}/db/db.sqlite3'
if not os.path.exists(os.path.dirname(db_path)):
    os.makedirs(os.path.dirname(db_path))
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(db_path),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = f'{BASE_DIR}/static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


error_log_path =  f'{BASE_DIR}/log/error.log'
debug_log_path = f'{BASE_DIR}/log/debug.log'
activity_log_path = f'{BASE_DIR}/log/activity.log'


error_log_dir = os.path.dirname(error_log_path)
debug_log_dir = os.path.dirname(debug_log_path)
activity_log_dir = os.path.dirname(activity_log_path)

if not os.path.exists(error_log_dir):
    os.makedirs(error_log_dir)
if not os.path.exists(debug_log_dir):
    os.makedirs(debug_log_dir)
if not os.path.exists(activity_log_dir):
    os.makedirs(activity_log_dir)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'error': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': error_log_path,
            'formatter': 'simple',
        },
        "debug": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            'filename': debug_log_path,
            'formatter': 'simple',
        },
        "activity":{
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": activity_log_path,
            "formatter": "simple",
        }
    },
    'loggers': {
        'django':{
            'handlers': ['debug'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error'],
            'level': 'ERROR',
            'propagate': False,
        },
        'activity':{
            'handlers': ['activity'],
            'level': 'INFO',
            'propagate': False,
        }
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}

#
AUTHENTICATION_BACKENDS = (
    'rules.permissions.ObjectPermissionBackend',
    'mgmt.backends.CSMUModelBackend',
)

MEDIA_URL = '/media/'

WHISPER_MODEL_PATH = os.getenv("WHISPER_MODEL_PATH", os.path.join(BASE_DIR, 'backend_api/models/whisper-v3-ct2'))

OUTPUT_ROOT_DIR = os.getenv("OUTPUT_ROOT_DIR", BASE_DIR)
os.makedirs(OUTPUT_ROOT_DIR, exist_ok=True)

MEDIA_DIR = os.getenv("MEDIA_DIR", os.path.join(OUTPUT_ROOT_DIR, 'media'))
os.makedirs(MEDIA_DIR, exist_ok=True)

AUDIO_DIR = os.getenv("AUDIO_DIR", os.path.join(MEDIA_DIR, 'audios'))
os.makedirs(AUDIO_DIR, exist_ok=True)

PICTURE_DIR = os.getenv("PICTURE_DIR", os.path.join(MEDIA_DIR, 'pictures'))
os.makedirs(PICTURE_DIR, exist_ok=True)

LINLY_TALKER_CHECKPOINTS_DIR = os.getenv("LINLY_TALKER_CHECKPOINTS_DIR", os.path.join(BASE_DIR, 'backend_api/linly_talker/checkpoints'))
os.makedirs(LINLY_TALKER_CHECKPOINTS_DIR, exist_ok=True)

LINLY_TALKER_CONFIG_DIR = os.getenv("LINLY_TALKER_CONFIG_DIR", os.path.join(BASE_DIR, 'backend_api/linly_talker/src/config'))
os.makedirs(LINLY_TALKER_CONFIG_DIR, exist_ok=True)

OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://192.168.0.46:11444/")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "alibayram/medgemma")

EXTERNAL_IP = os.getenv("EXTERNAL_IP", "192.168.0.132")
